# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_period', models.DecimalField(decimal_places=2, default=90, max_digits=10)),
                ('medium_period', models.DecimalField(decimal_places=2, default=75, max_digits=10)),
                ('low_period', models.DecimalField(decimal_places=2, default=60, max_digits=10)),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='period',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.Period'),
        ),
    ]
